# Generated by Django 3.2.6 on 2021-10-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.CharField(max_length=20, null=True, verbose_name='Forces')),
                ('latitude', models.FloatField(max_length=10, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(max_length=10, null=True, verbose_name='longitude')),
                ('information', models.CharField(max_length=200, null=True, verbose_name='Info')),
                ('image_url', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
    ]
