# Generated by Django 3.2.6 on 2021-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='map',
            name='state',
            field=models.CharField(max_length=30, null=True, verbose_name='State'),
        ),
    ]
