# Generated by Django 3.2.6 on 2021-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0002_auto_20211004_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='force',
            field=models.CharField(choices=[('A', 'Army'), ('AF', 'Navy'), ('N', 'Airforce')], max_length=2, null=True),
        ),
    ]
