# Generated by Django 3.2.6 on 2021-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0003_alter_map_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='command',
            field=models.CharField(choices=[('W', 'Western Command'), ('E', 'Eastern Command'), ('N', 'Northern Command'), ('S', 'Southern Command')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='force',
            field=models.CharField(choices=[('A', 'Army'), ('N', 'Navy'), ('AF', 'Airforce')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
