# Generated by Django 3.2.6 on 2021-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0004_auto_20211006_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('className', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='navyImages/', verbose_name='Image')),
                ('type', models.CharField(max_length=30, null=True)),
                ('shipName', models.CharField(max_length=30, null=True)),
                ('origin', models.CharField(max_length=30, null=True)),
                ('displacememt', models.CharField(max_length=30, null=True)),
                ('info', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='command',
            field=models.CharField(choices=[('W', 'Western Command'), ('E', 'Eastern Command'), ('N', 'Northern Command'), ('S', 'Southern Command'), ('C', 'Central Command'), ('SW', 'South Western Command')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
