# Generated by Django 3.2.6 on 2021-10-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0005_auto_20211031_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navy',
            name='className',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navy',
            name='displacememt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navy',
            name='origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navy',
            name='shipName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navy',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navy',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
