# Generated by Django 3.2.6 on 2021-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0006_auto_20211031_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navy',
            name='info',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
