# Generated by Django 3.2.6 on 2021-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0007_alter_navy_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airforce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('aircraftName', models.CharField(max_length=50, null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('variant', models.CharField(max_length=50, null=True)),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
