# Generated by Django 3.2.6 on 2021-11-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0008_airforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='airforce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='airforceImages/', verbose_name='Image'),
        ),
    ]
