# Generated by Django 3.2.6 on 2021-11-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0010_alter_airforce_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('subtitle', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('caliber', models.CharField(max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='armyImages/', verbose_name='Image')),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
