# Generated by Django 3.2.6 on 2021-11-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0011_army'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='army',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='army',
            name='title',
        ),
    ]
