# Generated by Django 3.2.6 on 2021-11-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0012_auto_20211109_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aran_api.subtype'),
        ),
        migrations.AddField(
            model_name='army',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aran_api.title'),
        ),
    ]
