# Generated by Django 3.2.6 on 2021-11-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0013_auto_20211109_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='title',
        ),
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aran_api.title'),
        ),
    ]
