# Generated by Django 3.2.6 on 2021-11-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0014_auto_20211109_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='aran_api.title'),
            preserve_default=False,
        ),
    ]
