# Generated by Django 3.2.6 on 2021-11-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0015_alter_subtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
