# Generated by Django 3.2.6 on 2021-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0016_alter_subtype_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='caliber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
