# Generated by Django 3.2.6 on 2021-12-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0019_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
