# Generated by Django 3.2.6 on 2022-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0020_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/', verbose_name='Image'),
        ),
    ]
