# Generated by Django 3.2.6 on 2022-01-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0022_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created',
        ),
    ]
