# Generated by Django 3.2.6 on 2022-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aran_api', '0025_alter_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.CharField(choices=[('A', 'Army'), ('N', 'Navy'), ('AF', 'Airforce')], max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
